### PR TITLE
Logging tweaks, restart consistency fixes, media.source option

### PR DESCRIPTION
**Pull request by achbed**
Additional logging when a station was found stopped and will never be restarted
Better description in logging station initialization errors
Internal station name and status filenames will no longer be regenerated on automatic station restart

### CODE REVIEW

**Comment by achbed** [comment]
Updated description for clarity

**Comment by achbed** [comment]
Added new code to merge ideas from ChoiZ's mode_playing branch

**Comment by yomguy** [comment]
Great changes as usual @achbed, thanks a lot!
And @ChoiZ will love it! ;)

**Comment by ChoiZ** [comment]
Yeah!

**Pull request merged**
