### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by ChoiZ**
automaTically instead of automaGically (but it can be magical ;))

### CODE REVIEW

**Comment by achbed** [comment]
the "g" was intentional, but unfortunately doesn't pass most spellchecks :)

**Comment by ChoiZ** [comment]
Ok if it was intentional. By reading it jumped out at me ;-)

**Comment by achbed** [comment]
Fixing to "automatically" in the readme is fine.

**Comment by yomguy** [comment]
Magic is everywhere ;)

**Comment by ChoiZ** [comment]
Well done! Thanks @achbed @yomguy.
Everywhere in this project :+1:

**Pull request merged**
