### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by ChoiZ**

### CODE REVIEW

**Comment by ChoiZ** [comment]
@yomguy you don't want to clean trailing whitespace?

**Comment by yomguy** [comment]
As the 0.7 release has happened, could you please provide this cleanup against the dev branch which prepare the 0.7.1 release? Thanks ;)

**Comment by yomguy** [comment]
yes I want! But I can't a release for that. Sorry if I have missed it just befoire the release. I was concentrate on the documentation. As this PR as conflicts, could you reproduce the cleanup against the dev branch ?

**Comment by ChoiZ** [comment]
Ok I'll recreate another PR.

**Comment by yomguy** [comment]
Thanks

**Pull request closed without merging**
